GET http://localhost:3001/members
###
GET http://localhost:3001/members/64eaa266f49ccae6eb463859

###

POST http://localhost:3001/members
Content-Type: application/json

{
    "name": "XYZ",
    "email": "xyz@gmail.com"
}

###

PATCH http://localhost:3001/members/64eaa266f49ccae6eb463859
Content-Type: application/json

{
    "name": "Gustof Courtney"
}